name: Build ip_set

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout ipset
      run: |
        git clone https://git.netfilter.org/ipset

    - name: apt
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool
        sudo apt-get install libmnl-dev

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b

    - name: Build ipset
      run: |
        cd ipset
        export NDK_PATH=${{steps.setup-ndk.outputs.ndk-path}}
        export PATH=$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export CC=aarch64-linux-android34-clang
        export LD=aarch64-linux-android-ld
        export CFLAGS="-I/usr/include/libmnl"
        autoreconf -vif
        ./configure --host=aarch64-linux-android --prefix=$PWD/install --enable-static --disable-shared
        make
        make install

    - name: Upload Gloom
      uses: actions/upload-artifact@v4
      with:
        name: Gloom
        path: "./ipset/install"
