name: Build Revanced bilibili

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: BiliRoamingX/BiliRoamingX
        ref: main
        path: BiliRoamingX
        fetch-depth: 0

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'oracle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Retrieve version
      run: |
        cd BiliRoamingX
        version=`awk -F "=" '$1 == "version" {print $2}' gradle.properties`
        commit_count=`git rev-list main --count`
        version="${version}.r${commit_count}"
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Build BiliRoamingX
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        cd BiliRoamingX
        ./gradlew --no-daemon -Pversion=$VERSION dist
        
    - name: Move to specified directory
      run: |
        mv ./BiliRoamingX/build .

    - name: Prepare bilibili apk
      run: |
        mkdir apk-jar
        cd apk-jar
        wget -qq https://github.com/REAndroid/APKEditor/releases/download/V1.3.7/APKEditor-1.3.7.jar
        mkdir temp
        cd temp
        wget -qq https://github.com/nekoaoxiang/build/releases/download/3.18.2/bilibili.zip
        unzip bilibili.zip
        rm -rf bilibili.zip
        cd ..
        java -jar APKEditor*.jar m -i ./temp
        mv *.apk ../build/bilibili.apk

    - name: Build bilibili
      run: |
        cd build
        wget -qq https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar
        java -jar revanced-cli.jar patch --merge integrations*.apk --patch-bundle patches*.jar --signing-levels 2,3 bilibili.apk

    - name: Upload bilibili
      uses: actions/upload-artifact@v4
      with:
        name: bilibili
        path: "./build"
