name: Build bilibili

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: download file
      run: |
        wget -qq https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v1.22.4/BiliRoamingX-integrations-1.22.4.apk
        wget -qq https://github.com/BiliRoamingX/BiliRoamingX/releases/download/v1.22.4/BiliRoamingX-patches-1.22.4.jar
        wget -qq https://github.com/zjns/revanced-cli/releases/download/v4.6.0.1/revanced-cli.jar
        wget -qq https://github.com/nekoaoxiang/build/releases/download/3.19.2/bilibili.apk
    - name: Build bilibili
      run: |
        java -jar revanced-cli.jar patch --merge BiliRoamingX-integrations*.apk --patch-bundle BiliRoamingX-patches*.jar --signing-levels 3 bilibili.apk

    - name: Upload bilibili
      uses: actions/upload-artifact@v4
      with:
        name: bilibili
        path: "./"
